task_name = UMG1_AMNet
model_save_dir = {your_save_path}/{task_name}   # your address to save model parameters

modality = RGB,kpt
frames_root = {your_dataset_root}/color_hand_norm,{your_dataset_root}/depth_hand_norm
train_label_file = {your_file_root}/train_UMG_gesture1.csv
eval_label_file_root = {your_file_root}
eval_label_files = test_cross_session_SG_gesture1.csv
frames_per_video = 64

model_path = AMNet  # take src/model as the root directory
model_name = Model_AMNet

optimizer = adam
